//
//  Sessions.swift
//  MindAndBody
//
//  Created by Luke Smith on 04.12.17.
//  Copyright © 2017 Luke Smith. All rights reserved.
//

import Foundation

extension sessionData {
    //
    //    static let presets: [[[]]]] =
    //    [
    //        "warmup":
    //            [
    //            "fullBody": ,
    //            "upperBody": ,
    //            "lowerBody": ,
    //            "cardio": ,
    //            ],
    //        "workout":
    //            [
    //            // Classic
    //            "classicGym": ,
    //            "classicGymUpper": ,
    //            "classicGymLower": ,
    //            "classicGymLegs": ,
    //            "classicGymPull": ,
    //            "classicGymPush": ,
    //            "classicGym5x5": ,
    //            // Circuit
    //            "circuitGymFull": ,
    //            "circuitGymUpper": ,
    //            "circuitGymLower": ,
    //            // BodyWeight Classic
    //            "classicBodyweightFull": ,
    //            "classicBodyweightUpper": ,
    //            "classicBodyweightLower": ,
    //            // Bodyweight circuit
    //            "circuitBodyweightFull": ,
    //            "circuitBodyweightUpper": ,
    //            "circuitBodyweightLower": ,
    //            ],
    //        "cardio":
    //            [
    //            "rowing": ,
    //            "biking": ,
    //            "running": ,
    //            ],
    //        "stretching": ,
    //            [
    //            "general": ,
    //            "postWorkout": ,
    //            "postCardio": ,
    //            ],
    //        "yoga":
    //            [
    //            "practices": ,
    //            ]
    //    ]
    
    
    // MARK: Notes
    // Session names have to be the same as their key
    // The first movement of a session contains extra information, title, number of rounds etc
    //
    
    // MARK:- Sessions
    static let sessions: [String: [String: [String: [Int: [String: Any]]]]] =
        [
            // MARK:- Warmup
            "warmup": [
                // movement
                // sets
                // reps
                // time
                // MARK: Full
                "fullBody": [
                    "allMovements": [
                        0: ["title": "allMovements",
                            "movement": "5minCardio",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        1: ["movement": "wrist",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        2: ["movement": "elbow",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        3: ["movement": "shoulderR",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        4: ["movement": "neckR",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        5: ["movement": "waist",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        6: ["movement": "hip",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        7: ["movement": "knees",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        8: ["movement": "ankles",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        9: ["movement": "backf",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        10: ["movement": "thoracicSpine",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        11: ["movement": "lat",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        12: ["movement": "pecDelt",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        13: ["movement": "rearDelt",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        14: ["movement": "quadf",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        15: ["movement": "adductorf",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        16: ["movement": "hamstringf",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        17: ["movement": "glutef",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        18: ["movement": "calvef",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        19: ["movement": "itBand",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        20: ["movement": "standOnBall",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        21: ["movement": "gluteBridgewW",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        22: ["movement": "kneelingKickBackW",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        23: ["movement": "legsToSideSquat",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        24: ["movement": "standingGluteKickback",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        25: ["movement": "sideLegDrop",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        26: ["movement": "sideLegKick",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        27: ["movement": "scorpionKick",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        28: ["movement": "sideBend",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        29: ["movement": "catCow",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        30: ["movement": "legsToSideTwist",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        31: ["movement": "upperBackRotation",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        32: ["movement": "latStretch",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        33: ["movement": "lyingSideWindmill",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        34: ["movement": "wallSlides",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        35: ["movement": "wallReaches",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        36: ["movement": "shoulderRotationW",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        37: ["movement": "forearmWallSlides135",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        38: ["movement": "superManShoulder",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        39: ["movement": "scapulaPushup",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        40: ["movement": "facePull",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        41: ["movement": "externalRotation",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        42: ["movement": "internalRotation",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        43: ["movement": "shoulderDislocation",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        44: ["movement": "latPullover",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        45: ["movement": "seatedKneeDrop",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        46: ["movement": "mountainClimber",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        47: ["movement": "groinStretch",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        48: ["movement": "threadTheNeedle",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        49: ["movement": "butterflyPose",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        50: ["movement": "cossakSquat",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        51: ["movement": "hipHinges",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        52: ["movement": "lungeTwist",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        53: ["movement": "sideLegSwings",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        54: ["movement": "frontLegSwings",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        55: ["movement": "spiderManHipLiftOverheadReach",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        56: ["movement": "forefootBounces",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        57: ["movement": "jumpSquat",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        58: ["movement": "lunge",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        59: ["movement": "gluteKicks",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        60: ["movement": "aSkips",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        61: ["movement": "bSkips",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        62: ["movement": "grapeVines",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        63: ["movement": "lateralBound",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        64: ["movement": "straightLegBound",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        65: ["movement": "sprints",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        66: ["movement": "pushUp",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        67: ["movement": "pullUp",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                    ],
                    "testSession": [
                        0: ["title": "testSession",
                            "movement": "5minCardio",
                            "sets": 2,
                            "reps": "0",
                            "time": 2], // Length of time to perform the movement for, used for Time Sessions
                    ],
                ],
                // MARK: Upper
                "upperBody": [
                    "testSession": [
                        0: ["title": "testSession",
                            "movement": "5minCardio",
                            "sets": 2,
                            "reps": "",
                            "time": 2],
                    ],
                ],
                // MARK: Lower
                "lowerBody": [
                    "testSession": [
                        0: ["title": "testSession",
                            "movement": "5minCardio",
                            "sets": 2,
                            "reps": "",
                            "time": 2],
                    ],
                ],
                // MARK: Cardio
                "cardio": [
                    "testSession": [
                        0: ["title": "testSession",
                            "movement": "5minCardio",
                            "sets": 2,
                            "reps": "",
                            "time": 2],
                    ],
                ],
            ],
            // MARK:- Workouts
            "workout": [
                //MARK: Classic Gym
                // movements
                // sets
                // reps
                // MARK: Full
                "classicGymFull": [
                    "allMovements": [
                        0: ["title": "allMovements",
                            "movement": "squat",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        1: ["movement": "frontSquat",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        2: ["movement": "legPress",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        3: ["movement": "dumbellFrontSquat",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        4: ["movement": "legExtensions",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        5: ["movement": "deadlift",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        6: ["movement": "romanianDeadlift",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        7: ["movement": "weightedHipThrust",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        8: ["movement": "legCurl",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        9: ["movement": "oneLeggedDeadlift",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        10: ["movement": "gluteIsolationMachine",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        11: ["movement": "lungeDumbell",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        12: ["movement": "bulgarianSplitSquat",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        13: ["movement": "weightedStepUp",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        14: ["movement": "standingCalfRaise",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        15: ["movement": "seatedCalfRaise",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        16: ["movement": "pullDown",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        17: ["movement": "kneelingPullDown",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        18: ["movement": "pullDownMachine",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        19: ["movement": "bentOverRowBarbell",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        20: ["movement": "bentOverRowDumbell",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        21: ["movement": "tBarRow",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        22: ["movement": "rowMachine",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        23: ["movement": "latPullover",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        24: ["movement": "facePull",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        25: ["movement": "leaningBackPullDown",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        26: ["movement": "bentOverBarbellRow",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        27: ["movement": "shrugDumbell",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        28: ["movement": "hammerCurl",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        29: ["movement": "hammerCurlCable",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        30: ["movement": "curl",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        31: ["movement": "farmersCarry",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        32: ["movement": "reverseBarbellCurl",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        33: ["movement": "forearmCurl",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        34: ["movement": "benchPress",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        35: ["movement": "benchPressDumbell",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        36: ["movement": "semiInclineDumbellPress",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        37: ["movement": "chestPress",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        38: ["movement": "platePress",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        39: ["movement": "barbellKneelingPress",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        40: ["movement": "cableFly",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        41: ["movement": "dips",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        42: ["movement": "standingShoulderPressBarbell",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        43: ["movement": "standingShoulderPressDumbell",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        44: ["movement": "lateralRaise",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        45: ["movement": "frontRaise",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        46: ["movement": "closeGripBench",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        47: ["movement": "cableExtension",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        48: ["movement": "ropeExtension",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        49: ["movement": "cleanPress",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        50: ["movement": "bodyweightSquat",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        51: ["movement": "pistolSquat",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        52: ["movement": "skaterSquat",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        53: ["movement": "squatJump",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        54: ["movement": "sumoSquat",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        55: ["movement": "lunge",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        56: ["movement": "lungeJump",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        57: ["movement": "deadlift",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        58: ["movement": "singleLegDeadlift",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        59: ["movement": "gluteBridge",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        60: ["movement": "singleLegGluteBridge",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        61: ["movement": "kickBack",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        62: ["movement": "standingKickBack",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        63: ["movement": "calfRaise",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        64: ["movement": "contralateralLimbRaises",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        65: ["movement": "superMan",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        66: ["movement": "backHyperextension",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        67: ["movement": "doorFrameRow",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        68: ["movement": "superMan",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        69: ["movement": "backHyperextension",
                             "sets": 2,
                             "reps": "0",
                             "time": 2],
                        70: ["movement": "handStandTrap",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        71: ["movement": "pushup",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        72: ["movement": "trianglePushup",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        73: ["movement": "dolphinPushup",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        74: ["movement": "tricepExtensionsBodyweight",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        75: ["movement": "walkingPushup",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        76: ["movement": "downwardDogPushup",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        77: ["movement": "wallPushup",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        78: ["movement": "boxer",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        79: ["movement": "armCircles",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        80: ["movement": "plank",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        81: ["movement": "dynamicPlank",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        82: ["movement": "sidePlankW",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        83: ["movement": "pushupPlank",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        84: ["movement": "lSit",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        85: ["movement": "bicycleCrunch",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        86: ["movement": "divingHold",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        87: ["movement": "hipRaise",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        88: ["movement": "legHold",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        89: ["movement": "mountainClimbers",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        90: ["movement": "burpee",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        91: ["movement": "kickThroughBurpee",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        92: ["movement": "spiderPushup",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        93: ["movement": "crabWalk",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        94: ["movement": "jumpingJacks",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        95: ["movement": "tuckJump",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        96: ["movement": "bumKicks",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        97: ["movement": "kneeRaises",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        98: ["movement": "wallSit",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        99: ["movement": "toePress",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        100: ["movement": "staticLunge",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        101: ["movement": "chestSqueeze",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        102: ["movement": "pushupHold",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        103: ["movement": "pullupHold",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        104: ["movement": "ballPushup",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        105: ["movement": "bodweightRow",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        106: ["movement": "pullup",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        107: ["movement": "hangingLegRaise",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        108: ["movement": "tricepDip",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        109: ["movement": "bulgarianSplitSquat",
                            "sets": 2,
                            "reps": "0",
                            "time": 2],
                        110: ["movement": "boxJump",
                              "sets": 2,
                              "reps": "0",
                              "time": 2],
                        111: ["movement": "hipThrusts",
                              "sets": 2,
                              "reps": "0",
                              "time": 2],
                        112: ["movement": "stepUp",
                              "sets": 2,
                              "reps": "0",
                              "time": 2],
                    ],
                    "testSession": [
                        0: ["title": "testSession",
                            "movement": "",
                            "sets": 2,
                            "reps": ""],
                    ],
                ],
                // MARK: Upper
                "classicGymUpper": [
                    "testSession": [
                        0: ["title": "testSession",
                            "movement": "squat",
                            "sets": 2,
                            "reps": ""],
                    ],
                ],
                // MARK: Lower
                "classicGymLower": [
                    "testSession": [
                        0: ["title": "testSession",
                            "movement": "squat",
                            "sets": 2,
                            "reps": ""],
                    ],
                ],
                // MARK: Legs
                "classicGymLegs": [
                    "testSession": [
                        0: ["title": "testSession",
                            "movement": "squat",
                            "sets": 2,
                            "reps": ""],
                    ],
                ],
                // MARK: Pull
                "classicGymPull": [
                    "testSession": [
                        0: ["title": "testSession",
                            "movement": "squat",
                            "sets": 2,
                            "reps": ""],
                    ],
                ],
                // MARK: Push
                "classicGymPush": [
                    "testSession": [
                        0: ["title": "testSession",
                            "movement": "squat",
                            "sets": 2,
                            "reps": ""],
                    ],
                ],
                // MARK: 5 x 5
                "classicGym5x5": [
                    "testSession": [
                        0: ["title": "testSession",
                            "movement": "squat",
                            "sets": 2,
                            "reps": ""],
                    ],
                ],
                // MARK: Circuit Gym
                // NOTE: NUMBER OF
                // movement
                // rounds (1st only)
                // reps
                // MARK: Full
                "circuitGymFull": [
                    "testSession": [
                        // Round 1
                        0: ["title": "testSession",
                            "movement": "squat",
                            "rounds": 2, //MARK: NOTE: first movement contains number of rounds
                            "reps": ""],
                        1: ["movement": "squat",
                            "reps": ""],
                        // Round 2
                        2: ["movement": "squat",
                            "reps": ""],
                        3: ["movement": "squat",
                            "reps": ""],
                    ],
                ],
                // MARK: Upper
                "circuitGymUpper": [
                    "testSession": [
                        // Round 1
                        0: ["title": "testSession",
                            "movement": "squat",
                            "rounds": 2,
                            "reps": ""],
                        1: ["movement": "squat",
                            "reps": ""],
                        // Round 2
                        2: ["movement": "squat",
                            "reps": ""],
                        3: ["movement": "squat",
                            "reps": ""],
                    ],
                ],
                // MARK: Lower
                "circuitGymLower": [
                    "testSession": [
                        // Round 1
                        0: ["title": "testSession",
                            "movement": "squat",
                            "rounds": 2,
                            "reps": ""],
                        1: ["movement": "squat",
                            "reps": ""],
                        // Round 2
                        2: ["movement": "squat",
                            "reps": ""],
                        3: ["movement": "squat",
                            "reps": ""],
                    ],
                ],
                // MARK: Classic Bodyweight
                // movements
                // sets
                // reps
                // time
                // MARK: Full
                "classicBodyweightFull": [
                    "testSession": [
                        0: ["title": "testSession",
                            "movement": "bodyweightSquat",
                            "sets": 2,
                            "reps": "",
                            "time": 2],
                    ],
                ],
                // MARK: Upper
                "classicBodyweightUpper": [
                    "testSession": [
                        0: ["title": "testSession",
                            "movement": "bodyweightSquat",
                            "sets": 2,
                            "reps": "",
                            "time": 2],
                    ],
                ],
                // MARK: Lower
                "classicBodyweightLower": [
                    "testSession": [
                        0: ["title": "testSession",
                            "movement": "bodyweightSquat",
                            "sets": 2,
                            "reps": "",
                            "time": 2],
                    ],
                ],
                // MARK: Circuit Bodyweight
                // movement
                // rounds
                // reps
                // time
                // MARK: Full
                "circuitBodyweightFull": [
                    "testSession": [
                        // Round 1
                        0: ["title": "testSession",
                            "movement": "bodyweightSquat",
                            "rounds": 2,
                            "reps": "",
                            "time": 2],
                        1: ["movement": "bodyweightSquat",
                            "reps": "",
                            "time": 2],
                        // Round 2
                        2: ["movement": "bodyweightSquat",
                            "reps": "",
                            "time": 2],
                        3: ["movement": "bodyweightSquat",
                            "reps": "",
                            "time": 2],
                    ],
                ],
                // MARK: Upper
                "circuitBodyweightUpper": [
                    "testSession": [
                        // Round 1
                        0: ["title": "testSession",
                            "movement": "bodyweightSquat",
                            "rounds": 2,
                            "reps": "",
                            "time": 2],
                        1: ["movement": "bodyweightSquat",
                            "reps": "",
                            "time": 2],
                        // Round 2
                        2: ["movement": "bodyweightSquat",
                            "reps": "",
                            "time": 2],
                        3: ["movement": "bodyweightSquat",
                            "reps": "",
                            "time": 2],
                    ],
                ],
                // MARK: Lower
                "circuitBodyweightLower": [
                    "testSession": [
                        // Round 1
                        0: ["title": "testSession",
                            "movement": "bodyweightSquat",
                            "rounds": 2,
                            "reps": "",
                            "time": 2],
                        1: ["movement": "bodyweightSquat",
                            "reps": "",
                            "time": 2],
                        // Round 2
                        2: ["movement": "bodyweightSquat",
                            "reps": "",
                            "time": 2],
                        3: ["movement": "bodyweightSquat",
                            "reps": "",
                            "time": 2],
                    ],
                ],
            ],
            // MARK:- Cardio
            "cardio": [
                    // MARK: Rowing
                "rowing": [
                    "testSession": [
                        0: ["title": "testSession",
                            "timeBased": true,
                            "movement": "sprintR", // Indicates if movement or pause
                            "length": 200], // Distanct/Time
                        1: ["movement": "slowR",
                            "length": 200,
                            "time": 10],
                        2: ["movement": "sprintR",
                            "length": 200,
                            "time": 10],
                        3: ["movement": "slowR",
                            "length": 200,
                            "time": 10],
                    ],
                    "testSession2": [
                        0: ["title": "testSession",
                            "timeBased": false,
                            "movement": "sprintR",
                            "length": 200,], // NOTE: Infomration indicating wether time based or distance based session found in first movement of session
                        1: ["movement": "slowR",
                            "length": 200,
                            "time": 10],
                        2: ["movement": "sprintR",
                            "length": 200,
                            "time": 10],
                        3: ["movement": "slowR",
                            "length": 200,
                            "time": 10],
                    ],
                ],
                    // MARK: Biking
                "biking": [
                    "testSession": [
                        0: ["title": "testSession",
                            "timeBased": true,
                            "movement": "sprintB",
                            "length": 200],
                        1: ["movement": "slowB",
                            "length": 200,
                            "time": 10],
                    ],
                ],
                    // MARK: Running
                "running": [
                    "testSession": [
                        0: ["title": "testSession",
                            "timeBased": true,
                            "movement": "sprint",
                            "length": 200],
                        1: ["movement": "slowJog",
                            "length": 200,
                            "time": 10],
                    ],
                ],
            ],
            // MARK:- Stretching
            "stretching": [
                "general": [
                    "allMovements": [
                        0: ["title": "allMovements",
                            "movement": "5minCardioL",
                            "breaths": 10,
                            "time": 2],
                        1: ["movement": "wrist",
                            "breaths": 10,
                            "time": 2],
                        2: ["movement": "elbow",
                            "breaths": 10,
                            "time": 2],
                        3: ["movement": "shoulderR",
                            "breaths": 10,
                            "time": 2],
                        4: ["movement": "neckR",
                            "breaths": 10,
                            "time": 2],
                        5: ["movement": "waist",
                            "breaths": 10,
                            "time": 2],
                        6: ["movement": "hip",
                            "breaths": 10,
                            "time": 2],
                        7: ["movement": "knees",
                            "breaths": 10,
                            "time": 2],
                        8: ["movement": "ankles",
                            "breaths": 10,
                            "time": 2],
                        9: ["movement": "backf",
                            "breaths": 10,
                            "time": 2],
                        10: ["movement": "thoracicSpine",
                             "breaths": 10,
                             "time": 2],
                        11: ["movement": "lat",
                             "breaths": 10,
                             "time": 2],
                        12: ["movement": "pecDelt",
                             "breaths": 10,
                             "time": 2],
                        13: ["movement": "rearDelt",
                             "breaths": 10,
                             "time": 2],
                        14: ["movement": "quadf",
                             "breaths": 10,
                             "time": 2],
                        15: ["movement": "adductorf",
                             "breaths": 10,
                             "time": 2],
                        16: ["movement": "hamstringf",
                             "breaths": 10,
                             "time": 2],
                        17: ["movement": "glutef",
                             "breaths": 10,
                             "time": 2],
                        18: ["movement": "calvef",
                             "breaths": 10,
                             "time": 2],
                        19: ["movement": "itBand",
                             "breaths": 10,
                             "time": 2],
                        20: ["movement": "standOnBall",
                             "breaths": 10,
                             "time": 2],
                        21: ["movement": "catCow",
                             "breaths": 10,
                             "time": 2],
                        22: ["movement": "upwardsDog",
                             "breaths": 10,
                             "time": 2],
                        23: ["movement": "extendedPuppy",
                             "breaths": 10,
                             "time": 2],
                        24: ["movement": "childPose",
                             "breaths": 10,
                             "time": 2],
                        25: ["movement": "staffPose",
                             "breaths": 10,
                             "time": 2],
                        26: ["movement": "pelvicTilt",
                             "breaths": 10,
                             "time": 2],
                        27: ["movement": "kneeToChest",
                             "breaths": 10,
                             "time": 2],
                        28: ["movement": "legDrop",
                             "breaths": 10,
                             "time": 2],
                        29: ["movement": "seatedTwist",
                             "breaths": 10,
                             "time": 2],
                        30: ["movement": "legsWall",
                             "breaths": 10,
                             "time": 2],
                        31: ["movement": "sideLean",
                             "breaths": 10,
                             "time": 2],
                        32: ["movement": "extendedSideAngle",
                             "breaths": 10,
                             "time": 2],
                        33: ["movement": "seatedSide",
                             "breaths": 10,
                             "time": 2],
                        34: ["movement": "rearNeck",
                             "breaths": 10,
                             "time": 2],
                        35: ["movement": "rearNeckHand",
                             "breaths": 10,
                             "time": 2],
                        36: ["movement": "seatedLateral",
                             "breaths": 10,
                             "time": 2],
                        37: ["movement": "neckRotator",
                             "breaths": 10,
                             "time": 2],
                        38: ["movement": "scalene",
                             "breaths": 10,
                             "time": 2],
                        39: ["movement": "headRoll",
                             "breaths": 10,
                             "time": 2],
                        40: ["movement": "forearmStretch",
                             "breaths": 10,
                             "time": 2],
                        41: ["movement": "tricepStretch",
                             "breaths": 10,
                             "time": 2],
                        42: ["movement": "bicepStretch",
                             "breaths": 10,
                             "time": 2],
                        43: ["movement": "pecStretch",
                             "breaths": 10,
                             "time": 2],
                        44: ["movement": "shoulderRoll",
                             "breaths": 10,
                             "time": 2],
                        45: ["movement": "behindBackTouch",
                             "breaths": 10,
                             "time": 2],
                        46: ["movement": "frontDelt",
                             "breaths": 10,
                             "time": 2],
                        47: ["movement": "lateralDelt",
                             "breaths": 10,
                             "time": 2],
                        48: ["movement": "rearDelt",
                             "breaths": 10,
                             "time": 2],
                        49: ["movement": "rotatorCuff",
                             "breaths": 10,
                             "time": 2],
                        50: ["movement": "squatHold",
                             "breaths": 10,
                             "time": 2],
                        51: ["movement": "groinStretch",
                             "breaths": 10,
                             "time": 2],
                        52: ["movement": "butterflyPose",
                             "breaths": 10,
                             "time": 2],
                        53: ["movement": "lungeStretch",
                             "breaths": 10,
                             "time": 2],
                        54: ["movement": "threadTheNeedle",
                             "breaths": 10,
                             "time": 2],
                        55: ["movement": "pigeonPose",
                             "breaths": 10,
                             "time": 2],
                        56: ["movement": "seatedGlute",
                             "breaths": 10,
                             "time": 2],
                        57: ["movement": "calveStretch",
                             "breaths": 10,
                             "time": 2],
                        58: ["movement": "standingHamstring",
                             "breaths": 10,
                             "time": 2],
                        59: ["movement": "standingOneLegHamstring",
                             "breaths": 10,
                             "time": 2],
                        60: ["movement": "downWardsDog",
                             "breaths": 10,
                             "time": 2],
                        61: ["movement": "singleLegHamstring",
                             "breaths": 10,
                             "time": 2],
                        62: ["movement": "twoLegHamstring",
                             "breaths": 10,
                             "time": 2],
                        63: ["movement": "lungeStretchWall",
                             "breaths": 10,
                             "time": 2],
                        64: ["movement": "quadStretch",
                             "breaths": 10,
                             "time": 2],
                        65: ["movement": "sumoSquatTwist",
                             "breaths": 10,
                             "time": 2],
                        66: ["movement": "tinyFencerStretch",
                             "breaths": 10,
                             "time": 2],
                    ],
                    "testSession": [
                        0: ["title": "testSession",
                            "movement": "kneeToChest",
                            "breaths": 10,
                            "time": 10], // Used for timed sessions
                    ],
                ],
                // MARK: !!!!!!!!!!!!!
                "hamstring": [
                    "testSession": [
                        0: ["title": "testSession",
                            "movement": "kneeToChest",
                            "breaths": 10,
                            "time": 10], // Used for timed sessions
                    ],
                ],
                // MARK: Post Workout
                "postWorkout": [
                    "testSession": [
                        0: ["title": "testSession",
                            "movement": "kneeToChest",
                            "breaths": 10,
                            "time": 10],
                    ],
                ],
                // MARK: Post Cardio
                "postCardio": [
                    "testSession": [
                        0: ["title": "testSession",
                            "movement": "kneeToChest",
                            "breaths": 10,
                            "time": 10],
                    ],
                ],
            ],
            // MARK:- Yoga
            "yoga": [
                    // MARK: Focus
                "practices": [
                    "allMovements": [
                        0: ["title": "allMovements",
                            "pose": "upwardsSalute",
                            "breaths": 10,
                            "time": 2],
                        1: ["pose": "mountain",
                            "breaths": 10,
                            "time": 2],
                        2: ["pose": "treeL",
                            "breaths": 10,
                            "time": 2],
                        3: ["pose": "treeR",
                            "breaths": 10,
                            "time": 2],
                        4: ["pose": "extendedToeGrabL",
                            "breaths": 10,
                            "time": 2],
                        5: ["pose": "extendedToeGrabR",
                            "breaths": 10,
                            "time": 2],
                        6: ["pose": "eagleL",
                            "breaths": 10,
                            "time": 2],
                        7: ["pose": "eagleR",
                            "breaths": 10,
                            "time": 2],
                        8: ["pose": "chair",
                            "breaths": 10,
                            "time": 2],
                        9: ["pose": "lordOfDanceL",
                            "breaths": 10,
                            "time": 2],
                        10: ["pose": "lordOfDanceR",
                             "breaths": 10,
                             "time": 2],
                        11: ["pose": "warrior1L",
                             "breaths": 10,
                             "time": 2],
                        12: ["pose": "warrior1R",
                             "breaths": 10,
                             "time": 2],
                        13: ["pose": "warrior2L",
                             "breaths": 10,
                             "time": 2],
                        14: ["pose": "warrior2R",
                             "breaths": 10,
                             "time": 2],
                        15: ["pose": "warrior3L",
                             "breaths": 10,
                             "time": 2],
                        16: ["pose": "warrior3R",
                             "breaths": 10,
                             "time": 2],
                        17: ["pose": "halfMoonL",
                             "breaths": 10,
                             "time": 2],
                        18: ["pose": "halfMoonR",
                             "breaths": 10,
                             "time": 2],
                        19: ["pose": "extendedTriangleL",
                             "breaths": 10,
                             "time": 2],
                        20: ["pose": "extendedTriangleR",
                             "breaths": 10,
                             "time": 2],
                        21: ["pose": "extendedSideAngleYL",
                             "breaths": 10,
                             "time": 2],
                        22: ["pose": "extendedSideAngleYR",
                             "breaths": 10,
                             "time": 2],
                        23: ["pose": "revolvedSideAngleL",
                             "breaths": 10,
                             "time": 2],
                        24: ["pose": "revolvedSideAngleR",
                             "breaths": 10,
                             "time": 2],
                        25: ["pose": "revolvedTriangleL",
                             "breaths": 10,
                             "time": 2],
                        26: ["pose": "revolvedTriangleR",
                             "breaths": 10,
                             "time": 2],
                        27: ["pose": "halfForwardBend",
                             "breaths": 10,
                             "time": 2],
                        28: ["pose": "forwardBend",
                             "breaths": 10,
                             "time": 2],
                        29: ["pose": "wideLeggedForwardBend",
                             "breaths": 10,
                             "time": 2],
                        30: ["pose": "intenseSideL",
                             "breaths": 10,
                             "time": 2],
                        31: ["pose": "intenseSideR",
                             "breaths": 10,
                             "time": 2],
                        32: ["pose": "gateL",
                             "breaths": 10,
                             "time": 2],
                        33: ["pose": "gateR",
                             "breaths": 10,
                             "time": 2],
                        34: ["pose": "highLungeL",
                             "breaths": 10,
                             "time": 2],
                        35: ["pose": "highLungeR",
                             "breaths": 10,
                             "time": 2],
                        36: ["pose": "lowLungeYL",
                             "breaths": 10,
                             "time": 2],
                        37: ["pose": "lowLungeYR",
                             "breaths": 10,
                             "time": 2],
                        38: ["pose": "deepSquat",
                             "breaths": 10,
                             "time": 2],
                        39: ["pose": "dolphin",
                             "breaths": 10,
                             "time": 2],
                        40: ["pose": "downwardDog",
                             "breaths": 10,
                             "time": 2],
                        41: ["pose": "halfDownwardDogL",
                             "breaths": 10,
                             "time": 2],
                        42: ["pose": "halfDownwardDogR",
                             "breaths": 10,
                             "time": 2],
                        43: ["pose": "dolphinPlank",
                             "breaths": 10,
                             "time": 2],
                        44: ["pose": "fourLimbedStaff",
                             "breaths": 10,
                             "time": 2],
                        45: ["pose": "sidePlankL",
                             "breaths": 10,
                             "time": 2],
                        46: ["pose": "sidePlankR",
                             "breaths": 10,
                             "time": 2],
                        47: ["pose": "cat",
                             "breaths": 10,
                             "time": 2],
                        48: ["pose": "cow",
                             "breaths": 10,
                             "time": 2],
                        49: ["pose": "catCow",
                             "breaths": 10,
                             "time": 2],
                        50: ["pose": "halfMonkeyL",
                             "breaths": 10,
                             "time": 2],
                        51: ["pose": "halfMonkeyR",
                             "breaths": 10,
                             "time": 2],
                        52: ["pose": "childPose",
                             "breaths": 10,
                             "time": 2],
                        53: ["pose": "wildThingL",
                             "breaths": 10,
                             "time": 2],
                        54: ["pose": "wildThingR",
                             "breaths": 10,
                             "time": 2],
                        55: ["pose": "upwardBow",
                             "breaths": 10,
                             "time": 2],
                        56: ["pose": "bridge",
                             "breaths": 10,
                             "time": 2],
                        57: ["pose": "upwardPlank",
                             "breaths": 10,
                             "time": 2],
                        58: ["pose": "extendedPuppy",
                             "breaths": 10,
                             "time": 2],
                        59: ["pose": "upwardDog",
                             "breaths": 10,
                             "time": 2],
                        60: ["pose": "crossLeg",
                             "breaths": 10,
                             "time": 2],
                        61: ["pose": "lotus",
                             "breaths": 10,
                             "time": 2],
                        62: ["pose": "fireLogL",
                             "breaths": 10,
                             "time": 2],
                        63: ["pose": "fireLogR",
                             "breaths": 10,
                             "time": 2],
                        64: ["pose": "boat",
                             "breaths": 10,
                             "time": 2],
                        65: ["pose": "cowFaceL",
                             "breaths": 10,
                             "time": 2],
                        66: ["pose": "cowFaceR",
                             "breaths": 10,
                             "time": 2],
                        67: ["pose": "hero",
                             "breaths": 10,
                             "time": 2],
                        68: ["pose": "butterfly",
                             "breaths": 10,
                             "time": 2],
                        69: ["pose": "staffPose",
                             "breaths": 10,
                             "time": 2],
                        70: ["pose": "seatedForwardBend",
                            "breaths": 10,
                            "time": 2],
                        71: ["pose": "vForwardBend",
                            "breaths": 10,
                            "time": 2],
                        72: ["pose": "vSideBendL",
                            "breaths": 10,
                            "time": 2],
                        73: ["pose": "vSideBendR",
                            "breaths": 10,
                            "time": 2],
                        74: ["pose": "halfVForwardBendL",
                            "breaths": 10,
                            "time": 2],
                        75: ["pose": "halfVForwardBendR",
                            "breaths": 10,
                            "time": 2],
                        76: ["pose": "halfVSideBendL",
                            "breaths": 10,
                            "time": 2],
                        77: ["pose": "halfVSideBendR",
                            "breaths": 10,
                            "time": 2],
                        78: ["pose": "marichi1L",
                            "breaths": 10,
                            "time": 2],
                        79: ["pose": "marichi1R",
                            "breaths": 10,
                            "time": 2],
                        80: ["pose": "marichi3L",
                            "breaths": 10,
                            "time": 2],
                        81: ["pose": "marichi3R",
                            "breaths": 10,
                            "time": 2],
                        82: ["pose": "frontSplitL",
                            "breaths": 10,
                            "time": 2],
                        83: ["pose": "frontSplitR",
                            "breaths": 10,
                            "time": 2],
                        84: ["pose": "sideSplit",
                            "breaths": 10,
                            "time": 2],
                        85: ["pose": "corpse",
                            "breaths": 10,
                            "time": 2],
                        86: ["pose": "fish",
                            "breaths": 10,
                            "time": 2],
                        87: ["pose": "happyBaby",
                            "breaths": 10,
                            "time": 2],
                        88: ["pose": "lyingButterfly",
                            "breaths": 10,
                            "time": 2],
                        89: ["pose": "legRaiseToeL",
                            "breaths": 10,
                            "time": 2],
                        90: ["pose": "legRaiseToeR",
                            "breaths": 10,
                            "time": 2],
                        91: ["pose": "threadTheNeedleL",
                            "breaths": 10,
                            "time": 2],
                        92: ["pose": "threadTheNeedleR",
                            "breaths": 10,
                            "time": 2],
                        93: ["pose": "shoulderStand",
                            "breaths": 10,
                            "time": 2],
                        94: ["pose": "plow",
                            "breaths": 10,
                            "time": 2],
                        95: ["pose": "cobra",
                            "breaths": 10,
                            "time": 2],
                        96: ["pose": "sphinx",
                            "breaths": 10,
                            "time": 2],
                        97: ["pose": "pigeonL",
                            "breaths": 10,
                            "time": 2],
                        98: ["pose": "pigeonR",
                            "breaths": 10,
                            "time": 2],
                        99: ["pose": "spineRolling",
                            "breaths": 10,
                            "time": 2],
                        100: ["pose": "handstand",
                            "breaths": 10,
                            "time": 2],
                        101: ["pose": "headstand",
                            "breaths": 10,
                            "time": 2],
                        102: ["pose": "forearmStand",
                            "breaths": 10,
                            "time": 2],
                    ],
                    "testSession": [
                        0: ["title": "testSession",
                            "pose": "forwardBend",
                            "breaths": 10],
                    ],
                ],
            ]
    ]
}
