//
//  Warmup.swift
//  MindAndBody
//
//  Created by Luke Smith on 24.02.19.
//  Copyright © 2019 Luke Smith. All rights reserved.
//

import Foundation

extension sessionData {
    
    // perform some initialization here
    // MARK:-
    // MARK:-
    // MARK:-
    // MARK:-
    // MARK:- Warmup
    // Note for warmup naming, -F means foam roller
    // Warmup Workout Short - Full - 1 (-F)
    //
    // movement
    // sets
    // reps
    // time
    static let WaW: [String: [[String: Any]]] = [
        "allMovements": [
            ["movement": "lightCardio"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "wrist"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "elbow"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "shoulderR"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "neckR"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "waist"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "hip"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "knees"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "ankles"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "backf"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "thoracicSpine"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "lat"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "pecDelt"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "rearDelt"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "quadf"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "adductorf"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "hamstringf"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "glutef"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "calff"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "itBand"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "standOnBall"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "gluteBridge"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "kneelingKickBackW"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "legsToSideSquat"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "standingGluteKickback"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "legDrop"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "sideLegKick"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "scorpionKick"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "sideBend"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "catCow"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "legsToSideTwist"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "upperBackRotation"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "latStretch"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "wallSlides"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "wallReaches"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "shoulderRotationW"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "forearmWallSlides135"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "superManShoulder"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "facePull"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "externalRotation"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "internalRotation"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "shoulderDislocation"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "latPullover"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "seatedKneeDrop"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "mountainClimber"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "groinStretch"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "threadTheNeedle"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "butterflyPose"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "cossakSquat"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "hipHinges"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "lungeTwist"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "sideLegSwings"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "frontLegSwings"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "hipLiftOverheadReach"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "forefootBounces"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "jumpSquat"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "lunge"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "gluteKicks"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "aSkips"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "bSkips"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "grapeVines"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "lateralBound"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "straightLegBound"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "sprints"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "pushUp"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
            ["movement": "pullUp"  as String,
             "sets": 2  as Int,
             "reps": "0"  as String,
             "time": 2  as Int],
        ] as [[String: Any]],
        
        // Note for warmup naming, -F at end means foam roller, Wa = warmup
        // Warmup Workout Short - Full - 1 (-F)
        
        // MARK:-
        // MARK:-
        // MARK: Workout
        // MARK:-
        // MARK: Full
        // MARK: Short
        "WaWS-F-1": [
            // Cardio
            ["movement": "lightCardio"  as String,
             "sets": 1  as Int,
             "reps": "2 min"  as String,
             "time": 120  as Int],
            // Joint Rotations
            ["movement": "wrist"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "elbow"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "legDrop"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Shoulder
            ["movement": "wallSlides"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
            // Cardio
            ["movement": "forefootBounces"  as String,
             "sets": 1  as Int,
             "reps": "30s"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
        "WaWS-F-2": [
            // Cardio
            ["movement": "lightCardio"  as String,
             "sets": 1  as Int,
             "reps": "2 min"  as String,
             "time": 120  as Int],
            // Joint Rotations
            ["movement": "wrist"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "elbow"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "legDrop"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Shoulder
            ["movement": "superManShoulder"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
            // Cardio
            ["movement": "lungeTwist"  as String,
             "sets": 1  as Int,
             "reps": "5-10"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
        "WaWS-F-3": [
            // Cardio
            ["movement": "lightCardio"  as String,
             "sets": 1  as Int,
             "reps": "2 min"  as String,
             "time": 120  as Int],
            // Joint Rotations
            ["movement": "wrist"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "elbow"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "legDrop"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Shoulder
            ["movement": "wallSlides"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
            // Cardio
            ["movement": "gluteKicks"  as String,
             "sets": 1  as Int,
             "reps": "30s"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
        "WaWS-F-4": [
            // Cardio
            ["movement": "lightCardio"  as String,
             "sets": 1  as Int,
             "reps": "2 min"  as String,
             "time": 120  as Int],
            // Joint Rotations
            ["movement": "wrist"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "elbow"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "legDrop"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Shoulder
            ["movement": "superManShoulder"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
            // Cardio
            ["movement": "aSkips"  as String,
             "sets": 1  as Int,
             "reps": "30s"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
        // MARK: Normal
        "WaWN-F-1": [
            // Cardio
            ["movement": "lightCardio"  as String,
             "sets": 1  as Int,
             "reps": "5 min"  as String,
             "time": 300  as Int],
            // Joint Rotations
            ["movement": "wrist"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "elbow"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "legDrop"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Shoulder
            ["movement": "wallSlides"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
            // Bounces
            ["movement": "forefootBounces"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
        "WaWN-F-2": [
            // Cardio
            ["movement": "lightCardio"  as String,
             "sets": 1  as Int,
             "reps": "5 min"  as String,
             "time": 300  as Int],
            // Joint Rotations
            ["movement": "wrist"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "elbow"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "sideLegKick"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Shoulder
            ["movement": "superManShoulder"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
            // Bounces
            ["movement": "lungeTwist"  as String,
             "sets": 1  as Int,
             "reps": "5-10"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
        "WaWN-F-3": [
            // Cardio
            ["movement": "lightCardio"  as String,
             "sets": 1  as Int,
             "reps": "5 min"  as String,
             "time": 300  as Int],
            // Joint Rotations
            ["movement": "wrist"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "elbow"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "legDrop"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Shoulder
            ["movement": "wallSlides"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
            // Bounces
            ["movement": "gluteKicks"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
        "WaWN-F-4": [
            // Cardio
            ["movement": "lightCardio"  as String,
             "sets": 1  as Int,
             "reps": "5 min"  as String,
             "time": 300  as Int],
            // Joint Rotations
            ["movement": "wrist"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "elbow"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "sideLegKick"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Shoulder
            ["movement": "superManShoulder"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
            // Bounces
            ["movement": "aSkips"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
        
        // MARK:-
        // MARK: Upper
        // MARK: Short
        "WaWS-U-1": [
            // Cardio
            ["movement": "lightCardio"  as String,
             "sets": 1  as Int,
             "reps": "2 min"  as String,
             "time": 120  as Int],
            // Joint Rotations
            ["movement": "wrist"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "elbow"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "shoulderRotationW"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "legDrop"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Shoulder
            ["movement": "wallSlides"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
        "WaWS-U-2": [
            // Cardio
            ["movement": "lightCardio"  as String,
             "sets": 1  as Int,
             "reps": "2 min"  as String,
             "time": 120  as Int],
            // Joint Rotations
            ["movement": "wrist"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "elbow"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "shoulderRotationW"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "sideLegKick"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Shoulder
            ["movement": "superManShoulder"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
        // MARK: Normal
        "WaWN-U-1": [
            // Cardio
            ["movement": "lightCardio"  as String,
             "sets": 1  as Int,
             "reps": "5 min"  as String,
             "time": 300  as Int],
            // Joint Rotations
            ["movement": "wrist"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "elbow"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 20  as Int],
            ["movement": "shoulderRotationW"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "upperBackRotation"  as String,
             "sets": 1  as Int,
             "reps": "5-10"  as String,
             "time": 15  as Int],
            ["movement": "legDrop"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Shoulder
            ["movement": "wallSlides"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
        "WaWN-U-2": [
            // Cardio
            ["movement": "lightCardio"  as String,
             "sets": 1  as Int,
             "reps": "5 min"  as String,
             "time": 300  as Int],
            // Joint Rotations
            ["movement": "wrist"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "elbow"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 20  as Int],
            ["movement": "shoulderRotationW"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "upperBackRotation"  as String,
             "sets": 1  as Int,
             "reps": "5-10"  as String,
             "time": 15  as Int],
            ["movement": "sideLegKick"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Shoulder
            ["movement": "superManShoulder"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
        
        // MARK:-
        // MARK: Lower
        // MARK: Short
        "WaWS-L-1": [
            // Cardio
            ["movement": "lightCardio"  as String,
             "sets": 1  as Int,
             "reps": "2 min"  as String,
             "time": 120  as Int],
            // Joint Rotations
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "legDrop"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Glutes
            ["movement": "gluteBridge"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
            // Ankles
            ["movement": "forefootBounces"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
        ] as [[String: Any]],
        "WaWS-L-2": [
            // Cardio
            ["movement": "lightCardio"  as String,
             "sets": 1  as Int,
             "reps": "2 min"  as String,
             "time": 120  as Int],
            // Joint Rotations
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "sideLegKick"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Glutes
            ["movement": "hipHinges"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
            // Ankles
            ["movement": "forefootBounces"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
        ] as [[String: Any]],
        "WaWS-L-3": [
            // Cardio
            ["movement": "lightCardio"  as String,
             "sets": 1  as Int,
             "reps": "2 min"  as String,
             "time": 120  as Int],
            // Joint Rotations
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "legDrop"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Glutes
            ["movement": "lungeTwist"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
            // Ankles
            ["movement": "forefootBounces"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
        ] as [[String: Any]],
        "WaWS-L-4": [
            // Cardio
            ["movement": "lightCardio"  as String,
             "sets": 1  as Int,
             "reps": "2 min"  as String,
             "time": 120  as Int],
            // Joint Rotations
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "sideLegKick"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Glutes
            ["movement": "cossakSquat"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
            // Ankles
            ["movement": "forefootBounces"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
        ] as [[String: Any]],
        // MARK: Normal
        "WaWN-L-1": [
            // Cardio
            ["movement": "lightCardio"  as String,
             "sets": 1  as Int,
             "reps": "5 min"  as String,
             "time": 300  as Int],
            // Joint Rotations
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "legDrop"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Glutes
            ["movement": "gluteBridge"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
            // Ankles
            ["movement": "forefootBounces"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
        ] as [[String: Any]],
        "WaWN-L-2": [
            // Cardio
            ["movement": "lightCardio"  as String,
             "sets": 1  as Int,
             "reps": "5 min"  as String,
             "time": 300  as Int],
            // Joint Rotations
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "sideLegKick"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Glutes
            ["movement": "hipHinges"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
            // Ankles
            ["movement": "forefootBounces"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
        ] as [[String: Any]],
        "WaWN-L-3": [
            // Cardio
            ["movement": "lightCardio"  as String,
             "sets": 1  as Int,
             "reps": "5 min"  as String,
             "time": 300  as Int],
            // Joint Rotations
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "legDrop"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Glutes
            ["movement": "lungeTwist"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
            // Ankles
            ["movement": "forefootBounces"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
        ] as [[String: Any]],
        "WaWN-L-4": [
            // Cardio
            ["movement": "lightCardio"  as String,
             "sets": 1  as Int,
             "reps": "5 min"  as String,
             "time": 300  as Int],
            // Joint Rotations
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "sideLegKick"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Glutes
            ["movement": "cossakSquat"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
            // Ankles
            ["movement": "forefootBounces"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
        ] as [[String: Any]],
    ] as [String: [[String: Any]]]
    
    // MARK:-
    // MARK:-
    // MARK: Endurance
    // MARK:-
    static let WaE: [String: [[String: Any]]] = [
        // Warmup Endurance Short - 1
        
        // MARK: Short
        "WaES-1": [
            // Joint Rotations
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10"  as String,
             "time": 20  as Int],
            ["movement": "lungeTwist"  as String,
             "sets": 1  as Int,
             "reps": "10"  as String,
             "time": 20  as Int],
            // Dynamic
            ["movement": "forefootBounces"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 30  as Int],
            ["movement": "aSkips"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
        "WaES-2": [
            // Joint Rotations
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10"  as String,
             "time": 20  as Int],
            ["movement": "lungeTwist"  as String,
             "sets": 1  as Int,
             "reps": "10"  as String,
             "time": 20  as Int],
            // Dynamic
            ["movement": "jumpSquat"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 30  as Int],
            ["movement": "gluteKicks"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
        "WaES-3": [
            // Joint Rotations
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10"  as String,
             "time": 20  as Int],
            ["movement": "lungeTwist"  as String,
             "sets": 1  as Int,
             "reps": "10"  as String,
             "time": 20  as Int],
            // Dynamic
            ["movement": "aSkips"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "grapeVines"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
        "WaES-4": [
            // Joint Rotations
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10"  as String,
             "time": 20  as Int],
            ["movement": "lungeTwist"  as String,
             "sets": 1  as Int,
             "reps": "10"  as String,
             "time": 20  as Int],
            // Dynamic
            ["movement": "aSkips"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "lateralBound"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
        // MARK: Normal
        "WaEN-1": [
            // Joint Rotations
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "lungeTwist"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Plank
            ["movement": "plank"  as String,
             "sets": 1  as Int,
             "reps": "10 breaths"  as String,
             "time": 30  as Int],
            // Dynamic
            ["movement": "forefootBounces"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 30  as Int],
            ["movement": "aSkips"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "lateralBound"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
        "WaEN-2": [
            // Joint Rotations
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "lungeTwist"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Plank
            ["movement": "plank"  as String,
             "sets": 1  as Int,
             "reps": "10 breaths"  as String,
             "time": 30  as Int],
            // Dynamic
            ["movement": "jumpSquat"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 30  as Int],
            ["movement": "gluteKicks"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "grapeVines"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
        "WaEN-3": [
            // Joint Rotations
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "lungeTwist"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Plank
            ["movement": "plank"  as String,
             "sets": 1  as Int,
             "reps": "10 breaths"  as String,
             "time": 30  as Int],
            // Dynamic
            ["movement": "gluteKicks"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 30  as Int],
            ["movement": "aSkips"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "lateralBound"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
    ] as [String: [[String: Any]]]
    
    // MARK:-
    // MARK:-
    // MARK: Flexibility/Yoga
    // MARK:-
    static let WaF: [String: [[String: Any]]] = [
        // MARK: Short
        "WaFS-1": [
            // Joint Rotations
            ["movement": "neckR"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Cardio
            ["movement": "forefootBounces"  as String,
             "sets": 1  as Int,
             "reps": "30s"  as String,
             "time": 30  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "legDrop"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
        "WaFS-2": [
            // Joint Rotations
            ["movement": "neckR"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Cardio
            ["movement": "aSkips"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "sideLegKick"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
        "WaFS-3": [
            // Joint Rotations
            ["movement": "neckR"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Cardio
            ["movement": "gluteKicks"  as String,
             "sets": 1  as Int,
             "reps": "30s"  as String,
             "time": 30  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "legDrop"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
        // MARK: Normal
        "WaFN-1": [
            // Joint Rotations
            ["movement": "elbow"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "neckR"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Cardio
            ["movement": "forefootBounces"  as String,
             "sets": 1  as Int,
             "reps": "30s"  as String,
             "time": 30  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "legDrop"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Shoulder
            ["movement": "wallSlides"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
        "WaFN-2": [
            // Joint Rotations
            ["movement": "elbow"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "neckR"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Cardio
            ["movement": "aSkips"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "sideLegKick"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Shoulder
            ["movement": "wallSlides"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
        "WaFN-3": [
            // Joint Rotations
            ["movement": "elbow"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "neckR"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "waist"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "knees"  as String,
             "sets": 1  as Int,
             "reps": "15s"  as String,
             "time": 15  as Int],
            ["movement": "ankles"  as String,
             "sets": 1  as Int,
             "reps": "20s"  as String,
             "time": 20  as Int],
            // Cardio
            ["movement": "gluteKicks"  as String,
             "sets": 1  as Int,
             "reps": "30s"  as String,
             "time": 30  as Int],
            // Back
            ["movement": "catCow"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            ["movement": "legDrop"  as String,
             "sets": 1  as Int,
             "reps": "10-15"  as String,
             "time": 30  as Int],
            // Shoulder
            ["movement": "wallSlides"  as String,
             "sets": 1  as Int,
             "reps": "15-20"  as String,
             "time": 30  as Int],
        ] as [[String: Any]],
    ] as [String: [[String: Any]]]
    
}
